[package]
name = "rust_m3"
authors = ["Robin Freyler <robin.freyler@gmail.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.bench]
lto = "fat"
codegen-units = 1
